package workspace

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"agyent/internal/core/domain"
	"agyent/internal/core/ports"
)

var _ ports.WorkspacePort = (*Manager)(nil)

// Windows reserved device names that cannot be used as file names
var windowsReservedNames = map[string]bool{
	"con": true, "prn": true, "aux": true, "nul": true,
	"com1": true, "com2": true, "com3": true, "com4": true,
	"com5": true, "com6": true, "com7": true, "com8": true, "com9": true,
	"lpt1": true, "lpt2": true, "lpt3": true, "lpt4": true,
	"lpt5": true, "lpt6": true, "lpt7": true, "lpt8": true, "lpt9": true,
}

// Manager implements ports.WorkspacePort for managing workspace directory trees,
// inbound upload staging relocation, and git isolation.
type Manager struct {
	logger *slog.Logger
}

// NewManager creates a new workspace manager instance.
func NewManager(logger *slog.Logger) *Manager {
	if logger == nil {
		logger = slog.Default()
	}
	return &Manager{
		logger: logger,
	}
}

// EnsureWorkspaceUploadsDir ensures that <workspaceDir>/uploads exists and contains a .gitignore.
func (m *Manager) EnsureWorkspaceUploadsDir(workspaceDir string) (string, error) {
	if workspaceDir == "" {
		return "", fmt.Errorf("workspace directory cannot be empty")
	}

	uploadsDir := filepath.Join(workspaceDir, "uploads")
	if err := os.MkdirAll(uploadsDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create workspace uploads directory %s: %w", uploadsDir, err)
	}

	gitignorePath := filepath.Join(uploadsDir, ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		content := "# Automatically generated by agyent to prevent inbound uploads from polluting git tracking\n*\n!.gitignore\n"
		if writeErr := os.WriteFile(gitignorePath, []byte(content), 0644); writeErr != nil {
			m.logger.Warn("Failed to write .gitignore to workspace uploads", "path", gitignorePath, "error", writeErr)
		}
	}

	return uploadsDir, nil
}

// SanitizeFilename cleans an inbound filename to prevent path traversal, null-byte injection,
// and Windows device name collisions.
func SanitizeFilename(name string) string {
	if name == "" {
		return "file"
	}

	// 1. Remove directory traversal tokens and delimiters
	cleaned := filepath.Base(name)
	cleaned = strings.ReplaceAll(cleaned, "..", "")
	cleaned = strings.ReplaceAll(cleaned, "/", "_")
	cleaned = strings.ReplaceAll(cleaned, "\\", "_")
	cleaned = strings.ReplaceAll(cleaned, "\x00", "")

	// 2. Trim trailing dots and whitespace
	cleaned = strings.Trim(cleaned, " .")
	if cleaned == "" {
		cleaned = "file"
	}

	// 3. Check Windows reserved device names (CON, PRN, AUX, NUL, COM1..9, LPT1..9)
	baseOnly := strings.ToLower(cleaned)
	if idx := strings.Index(baseOnly, "."); idx != -1 {
		baseOnly = baseOnly[:idx]
	}
	if windowsReservedNames[baseOnly] {
		cleaned = "safe_" + cleaned
	}

	return cleaned
}

// PrepareInboundAttachments relocates or copies attachments from staging into the active workspace.
func (m *Manager) PrepareInboundAttachments(ctx context.Context, workspaceDir string, attachments []domain.Attachment) ([]domain.Attachment, error) {
	if len(attachments) == 0 {
		return attachments, nil
	}

	uploadsDir, err := m.EnsureWorkspaceUploadsDir(workspaceDir)
	if err != nil {
		return attachments, err
	}

	cleanUploadsDir := filepath.Clean(uploadsDir)
	var prepared []domain.Attachment

	for _, att := range attachments {
		if att.FilePath == "" {
			prepared = append(prepared, att)
			continue
		}

		cleanSrc := filepath.Clean(att.FilePath)

		// If file is already inside target uploads dir, keep as is
		if isInsideDir(cleanSrc, cleanUploadsDir) {
			prepared = append(prepared, att)
			continue
		}

		// Verify source file exists
		srcInfo, err := os.Stat(cleanSrc)
		if err != nil {
			m.logger.Warn("Inbound attachment source file not found", "path", cleanSrc, "error", err)
			prepared = append(prepared, att)
			continue
		}

		// Determine safe destination filename
		rawName := att.FileName
		if rawName == "" {
			rawName = filepath.Base(cleanSrc)
		}
		safeBase := SanitizeFilename(rawName)
		destFileName := fmt.Sprintf("%d_%s", time.Now().UnixNano(), safeBase)
		destPath := filepath.Join(cleanUploadsDir, destFileName)

		// Move or Copy-then-Delete to handle cross-device links (EXDEV)
		if err := relocateFile(cleanSrc, destPath); err != nil {
			m.logger.Error("Failed to relocate inbound attachment to workspace", "src", cleanSrc, "dest", destPath, "error", err)
			prepared = append(prepared, att)
			continue
		}

		att.FilePath = destPath
		att.FileName = safeBase
		att.Size = srcInfo.Size()
		prepared = append(prepared, att)

		m.logger.Debug("Relocated inbound attachment to active workspace", "src", cleanSrc, "dest", destPath, "size", att.Size)
	}

	return prepared, nil
}

// relocateFile moves src to dst. If os.Rename fails (e.g. cross-device link), it falls back to Copy-then-Delete.
func relocateFile(src, dst string) error {
	// Attempt fast atomic rename first
	if err := os.Rename(src, dst); err == nil {
		return nil
	}

	// Fallback to Copy-then-Delete
	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("failed to open source file %s: %w", src, err)
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("failed to create dest file %s: %w", dst, err)
	}

	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		_ = os.Remove(dst)
		return fmt.Errorf("failed to copy file contents from %s to %s: %w", src, dst, err)
	}

	if err := out.Sync(); err != nil {
		out.Close()
		_ = os.Remove(dst)
		return fmt.Errorf("failed to sync dest file %s: %w", dst, err)
	}

	if err := out.Close(); err != nil {
		_ = os.Remove(dst)
		return fmt.Errorf("failed to close dest file %s: %w", dst, err)
	}

	// Close source before removing (critical on Windows)
	_ = in.Close()
	_ = os.Remove(src)

	return nil
}

// isInsideDir returns true if target is within base dir.
func isInsideDir(target, base string) bool {
	cTarget := filepath.Clean(target)
	cBase := filepath.Clean(base)
	if runtime.GOOS == "windows" {
		cTarget = strings.ToLower(cTarget)
		cBase = strings.ToLower(cBase)
	}
	if cTarget == cBase {
		return true
	}
	if !strings.HasSuffix(cBase, string(filepath.Separator)) {
		cBase += string(filepath.Separator)
	}
	return strings.HasPrefix(cTarget, cBase)
}
